#!/bin/bash -x

#-v /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:ro \

docker run \
	--rm \
	--name myjenkins \
	-p 8080:8080 \
	-p 5000:5000 \
	-v /home/ozlevka/tmp/jenkins-home:/var/jenkins_home \
	-e "GITHUB_TOKEN=" \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v $(which docker):/usr/bin/docker \
	-v /home/ozlevka/.kube:/root/.kube \
	--privileged=true \
	ozlevka/jenkins:latest
	#ozlevka/jenkins:190206-15.40

