#!/bin/bash -x

#-v /usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:ro \

docker run \
	-d \
	--name jenkins \
	-p 8080:8080 \
	-p 5000:5000 \
	-v $HOME/tmp/jenkins-home:/var/jenkins_home \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v $(which docker):/usr/bin/docker \
	-v $HOME/.aws:/root/.aws \
	-v $HOME/.kube:/root/.kube \
	--privileged=true \
	 724428538127.dkr.ecr.us-east-1.amazonaws.com/jenkins-master:2.249.3
#jenkins:latest
# latest 181107-17.08

